image: docker:latest
services:
  - name: docker:dind
    command: ["--insecure-registry=registry.gitlab.winllc-dev.com"]

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-14
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - jester-winllc-server/target/*.jar

package:
  stage: package
  script:
    - docker build -t registry.gitlab.winllc-dev.com/root/winllc-jester ./jester-winllc-server
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.winllc-dev.com
    - docker push registry.gitlab.winllc-dev.com/root/winllc-jester

deploy_staging:
  stage: deploy
  script:
    - apk upgrade && apk update
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.winllc-dev.com
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker pull registry.gitlab.winllc-dev.com/root/winllc-jester
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER "docker container stop winllc-jester && docker container rm winllc-jester || true"
    - sshpass -p "$STAGING_SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker run --name winllc-jester -p 8181:8181 -d registry.gitlab.winllc-dev.com/root/winllc-jester
  environment:
    name: staging
    url: http://winra.winllc-dev.com
  only:
    - winllc